name: feedmn
description: "FeedMN - A surplus food sharing app to reduce food waste and help communities"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  uuid: ^4.3.3
  envied: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  http: ^0.13.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"














